# Generated by Django 3.2.4 on 2021-07-28 09:31

import Textile_Market.textile_app.validators
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('textile_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.TextField(max_length=30)),
                ('quantity', models.IntegerField(validators=[Textile_Market.textile_app.validators.validate_quantity])),
                ('description', models.TextField(blank=True, max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textile_profile.profile')),
            ],
        ),
    ]
