# Generated by Django 3.2.4 on 2021-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
