# Generated by Django 3.2.4 on 2021-07-15 15:05

import Textile_Market.textile_app.validators
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffer',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='addoffer',
            name='quantity',
            field=models.IntegerField(validators=[Textile_Market.textile_app.validators.validate_quantity]),
        ),
    ]
