# Generated by Django 3.2.4 on 2021-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textile_app', '0002_auto_20210715_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoffer',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
